Repository ACMW-Manipal/acmw-website-24, pull requests merged in 2024-04, with the labels that each got.

#11 Recruitment page form
  join.html
Labels: level 3

#20 Fixed #8
  about.html
Labels: level 2

#22 fixed #1 board members
  index.html
Labels: level 3

#21 fix navbar at top of page
  events.html
  style.css
Labels: level 2

#30 Issue #4 Solved
  index.html
Labels: level 1

#32 Issue no. #6 is solved
  index.html
  style.css
Labels: level 1

#34 Event Calendar
  events.html
  style.css
Labels: level 3

#36 UI of about us page is improved
  about.html
Labels: level 1

#42 Fixed navbar bug
  events.html
  style.css
Labels: level 1

#43 picture gallery and Added members list table. FIxed#26 and #44
  .vscode/settings.json
  index.html
Labels: level 2

#29 Contributors Section
  github-logo.png
  index.html
  style.css
Labels: level 2
